# JOB-A-THON

## Health Insurance Lead Prediction

#### Problem Statement
Your Client FinMan is a financial services company that provides various financial services like loan, investment funds, insurance etc. to its customers. FinMan wishes to cross-sell health insurance to the existing customers who may or may not hold insurance policies with the company. The company recommend health insurance to it's customers based on their profile once these customers land on the website. Customers might browse the recommended health insurance policy and consequently fill up a form to apply. When these customers fill-up the form, their Response towards the policy is considered positive and they are classified as a lead.

Once these leads are acquired, the sales advisors approach them to convert and thus the company can sell proposed health insurance to these leads in a more efficient manner.


### Import Packages

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Dataset Import (training dataset)

In [2]:
dataset1=pd.read_csv('train_Df64byy.csv')
dataset=dataset1.drop(['ID'], axis = 1)
dataset.head(10)

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   
5        C9         1785            Rented          Individual         52   
6        C3          679             Owned          Individual         28   
7        C1         3175             Owned               Joint         75   
8       C15         3497             Owned               Joint         52   
9        C1          530             Owned               Joint         59   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   
5         52        No               X2                     5.0   
6         28        No              NaN                     NaN   
7         73       Yes               X4                     9.0   
8         43        No               X1                    14.0   
9         26       Yes              NaN                     7.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0  
5                  1.0               22              15264.0         1  
6                  NaN               17              10640.0         0  
7                  4.0               17              29344.0         1  
8                  3.0                1              27283.2         0  
9                  4.0               18              21100.8         1

### Dataset Dimention, Shape or Size

In [3]:
dataset.shape

(50882, 13)

In [4]:
# print the existing data type of each column 
dataset.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 13 columns):
City_Code                  50882 non-null object
Region_Code                50882 non-null int64
Accomodation_Type          50882 non-null object
Reco_Insurance_Type        50882 non-null object
Upper_Age                  50882 non-null int64
Lower_Age                  50882 non-null int64
Is_Spouse                  50882 non-null object
Health Indicator           39191 non-null object
Holding_Policy_Duration    30631 non-null object
Holding_Policy_Type        30631 non-null float64
Reco_Policy_Cat            50882 non-null int64
Reco_Policy_Premium        50882 non-null float64
Response                   50882 non-null int64
dtypes: float64(2), int64(5), object(6)
memory usage: 5.0+ MB


### Understanding the various features (columns) of the dataset. ###

In [5]:
dataset.describe()

Region_Code     Upper_Age     Lower_Age  Holding_Policy_Type  \
count  50882.000000  50882.000000  50882.000000         30631.000000   
mean    1732.788707     44.856275     42.738866             2.439228   
std     1424.081652     17.310271     17.319375             1.025923   
min        1.000000     18.000000     16.000000             1.000000   
25%      523.000000     28.000000     27.000000             1.000000   
50%     1391.000000     44.000000     40.000000             3.000000   
75%     2667.000000     59.000000     57.000000             3.000000   
max     6194.000000     75.000000     75.000000             4.000000   

       Reco_Policy_Cat  Reco_Policy_Premium      Response  
count     50882.000000         50882.000000  50882.000000  
mean         15.115188         14183.950069      0.239947  
std           6.340663          6590.074873      0.427055  
min           1.000000          2280.000000      0.000000  
25%          12.000000          9248.000000      0.000000  
50%          17.000000         13178.000000      0.000000  
75%          20.000000         18096.000000      0.000000  
max          22.000000         43350.400000      1.000000

### Find the NA or Missing Values and replace with Mean or Median

In [6]:
dataset=dataset.rename(columns={'Health Indicator': 'Health_Indicator'}) 

In [7]:
# Total missing values for each feature
print (dataset.isnull().sum())

City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health_Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64


We found the given dataset 3 variables are presente missing values. And we replace this 3 variables missing values with mean or Mode. (Note: the presence of missing value in numeric variable then we use mean or median for replace. otherwise mode for chategorical variable.)

filling a null values using IterativeInputer

In [8]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer

In [9]:
dataset.iloc[:,7:10].head(5)

Health_Indicator Holding_Policy_Duration  Holding_Policy_Type
0               X1                     14+                  3.0
1               X2                     NaN                  NaN
2              NaN                     1.0                  1.0
3               X1                     14+                  3.0
4               X2                     3.0                  1.0

In [10]:
from sklearn.impute import SimpleImputer
imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
dataset.iloc[:,7:10]=imp_mode.fit_transform(dataset.iloc[:,7:10])

In [11]:
dataset.iloc[:,7:10].head(5)

Health_Indicator Holding_Policy_Duration  Holding_Policy_Type
0               X1                     14+                  3.0
1               X2                     1.0                  3.0
2               X1                     1.0                  1.0
3               X1                     14+                  3.0
4               X2                     3.0                  1.0

In [12]:
# Now we can see all of the columns have non-null values
dataset.isnull().sum()

City_Code                  0
Region_Code                0
Accomodation_Type          0
Reco_Insurance_Type        0
Upper_Age                  0
Lower_Age                  0
Is_Spouse                  0
Health_Indicator           0
Holding_Policy_Duration    0
Holding_Policy_Type        0
Reco_Policy_Cat            0
Reco_Policy_Premium        0
Response                   0
dtype: int64

In [13]:
dataset.Response.value_counts()

0    38673
1    12209
Name: Response, dtype: int64

In [14]:
X = dataset.iloc[:,:-1].values
y = dataset['Response'].values

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X[:, 2] = le.fit_transform(X[:, 2])
X[:, 3] = le.fit_transform(X[:, 3])
X[:, 6] = le.fit_transform(X[:, 6])
X[:, 7] = le.fit_transform(X[:, 7])
X[:, 8] = le.fit_transform(X[:, 8])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40705, 12)
(10177, 12)
(40705,)
(10177,)


# Using Algorithm to develop an Optimum Model

## Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_lr))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_lr),2))


Confusion Matrix
[[7686    0]
 [2491    0]]
The model accuracy is  0.76


C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## Naive Bayes Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_nb))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_nb),2))

## Stochastic Gradient Descent

In [ ]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(shuffle=False)
sgd.fit(X_train, y_train)
y_pred_sgd = sgd.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_sgd))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_sgd),2))

## K-Nearest Neighbours (KNN Algorithm)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_knn))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_knn),2))

## Decision Tree Algorithm

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
y_pred_dtree = dtree.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_dtree))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_dtree),2))

## Random Forest Algorithm

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_rfc))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_rfc),2))

## Support Vector Machine

### Linear Kernel

In [ ]:
from sklearn.svm import SVC

svm_lin = SVC(kernel="linear")
svm_lin.fit(X_train, y_train)
y_pred_lin = svm_lin.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_lin))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_lin),2))

### RBF Kernel

In [23]:
svm_rbf = SVC(kernel="rbf")
svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_rbf))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_rbf),2))

Confusion Matrix
[[7686    0]
 [2491    0]]
The model accuracy is  0.76


### Sigmoid Kernel

In [24]:
svm_sig = SVC(kernel="sigmoid")
svm_sig.fit(X_train, y_train)
y_pred_sig = svm_sig.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_sig))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_sig),2))

Confusion Matrix
[[5852 1834]
 [1900  591]]
The model accuracy is  0.63


### Polynomial Kernel

In [25]:
svm_poly = SVC(kernel="poly")
svm_poly.fit(X_train, y_train)
y_pred_poly = svm_poly.predict(X_test)

print("Confusion Matrix")
print("="*30)
print(confusion_matrix(y_test, y_pred_poly))
print("The model accuracy is ", round(accuracy_score(y_test, y_pred_poly),2))

Confusion Matrix
[[7686    0]
 [2491    0]]
The model accuracy is  0.76


# Import Test Dataset and Classify the Response Variable

In [26]:
X_test_D=pd.read_csv('test_YCcRUnU.csv')
X_test_D=X_test_D.drop(['ID'], axis = 1)

X_test_D=X_test_D.rename(columns={'Health Indicator': 'Health_Indicator'}) 

# Total missing values for each feature
print (X_test_D.isnull().sum())

# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer

from sklearn.impute import SimpleImputer
imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X_test_D.iloc[:,7:10]=imp_mode.fit_transform(X_test_D.iloc[:,7:10])

X_test_D.iloc[:,7:10].head(5)

City_Code                     0
Region_Code                   0
Accomodation_Type             0
Reco_Insurance_Type           0
Upper_Age                     0
Lower_Age                     0
Is_Spouse                     0
Health_Indicator           5027
Holding_Policy_Duration    8603
Holding_Policy_Type        8603
Reco_Policy_Cat               0
Reco_Policy_Premium           0
dtype: int64


Health_Indicator Holding_Policy_Duration  Holding_Policy_Type
0               X1                     6.0                  3.0
1               X1                     3.0                  3.0
2               X3                     2.0                  4.0
3               X3                     3.0                  3.0
4               X3                     14+                  3.0

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X_test_D['City_Code'] = le.fit_transform(X_test_D['City_Code'])
X_test_D['Accomodation_Type'] = le.fit_transform(X_test_D['Accomodation_Type'])
X_test_D['Reco_Insurance_Type'] = le.fit_transform(X_test_D['Reco_Insurance_Type'])
X_test_D['Is_Spouse'] = le.fit_transform(X_test_D['Is_Spouse'])
X_test_D['Health_Indicator'] = le.fit_transform(X_test_D['Health_Indicator'])
X_test_D['Holding_Policy_Duration'] = le.fit_transform(X_test_D['Holding_Policy_Duration'])

In [32]:
y_pred_test = pd.DataFrame(svm_poly.predict(X_test_D))

### Data Export

In [33]:
y_pred_test.to_csv(r'E:\Job A Thon\Output\export_dataframe_svm_poly.csv', index = False, header=True)